name: C/C++ CI
on: [push, pull_request]

jobs:

  build-windows-msvc-qt6:
    name: Build Windows MSVC Qt 6
    runs-on: windows-latest
    steps:

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.29

      #- name: Install boost
      #  uses: MarkusJx/install-boost@v2.0.0
      #  with:
      #    boost_version: 1.73.0

      - name: Install protobuf
        run: vcpkg install protobuf

      - name: Copy protobuf headers
        run: xcopy /s c:\vcpkg\packages\protobuf_x64-windows\include\* c:\gstreamer\1.0\msvc_x86_64\include\

      - name: Install Qt 6
        uses: jurplel/install-qt-action@v2.14.0
        with:
          version: 6.1.3
          modules: qtbase qttools

      - name: Download Boost
        uses: suisei-cn/actions-download-file@v1
        with:
          url: "Boost [this](https://boostorg.jfrog.io/artifactory/main/release/1.77.0/source/boost_1_77_0.zip)!"
          target: downloads/
          auto-match: true

      #- name: Download Protobuf
      #  uses: suisei-cn/actions-download-file@v1
      #  with:
      #    url: "Protobuf [this](https://github.com/protocolbuffers/protobuf/releases/download/v3.18.0-rc2/protobuf-cpp-3.18.0-rc-2.zip)!"
      #    target: downloads/
      #    auto-match: true

      - name: Download SQLite
        uses: suisei-cn/actions-download-file@v1
        with:
          url: "SQLite [this](https://www.sqlite.org/2021/sqlite-autoconf-3360000.tar.gz)!"
          target: downloads/
          auto-match: true

      - name: Download GStreamer
        uses: suisei-cn/actions-download-file@v1
        with:
          url: "GStreamer [this](https://gstreamer.freedesktop.org/data/pkg/windows/1.18.5/msvc/gstreamer-1.0-msvc-x86_64-1.18.5.msi)!"
          target: downloads/
          auto-match: true

      - name: Download GStreamer Devel
        uses: suisei-cn/actions-download-file@v1
        with:
          url: "GStreamer Devel [this](https://gstreamer.freedesktop.org/data/pkg/windows/1.18.5/msvc/gstreamer-1.0-devel-msvc-x86_64-1.18.5.msi)!"
          target: downloads/
          auto-match: true

      - name: Download GnuTLS
        uses: suisei-cn/actions-download-file@v1
        with:
          url: "GnutTLS [this](https://github.com/ShiftMediaProject/gnutls/releases/download/3.7.2/libgnutls_3.7.2_msvc14.zip)!"
          target: downloads/
          auto-match: true

      - name: Download TagLib
        uses: suisei-cn/actions-download-file@v1
        with:
          url: "TagLib [this](https://taglib.org/releases/taglib-1.12.tar.gz)!"
          target: downloads/
          auto-match: true

      - name: Extract Boost
        working-directory: D:\a\strawberry\strawberry
        run: 7z x d:\a\strawberry\strawberry\downloads\boost_1_77_0.zip

      - name: Copy Boost
        shell: bash
        run: cp -r /d/a/strawberry/strawberry/boost_1_77_0/boost /c/gstreamer/1.0/msvc_x86_64/include/

      - name: Check Boost
        run: dir c:\gstreamer\1.0\msvc_x86_64\include\boost

      #- name: Extract Protobuf
      #  working-directory: D:\a\strawberry\strawberry
      #  run: 7z x d:\a\strawberry\strawberry\downloads\protobuf-cpp-3.18.0-rc-2.zip

      - name: Extract SQLite
        working-directory: D:\a\strawberry\strawberry
        shell: bash
        run: tar -xvf /d/a/strawberry/strawberry/downloads/sqlite-autoconf-3360000.tar.gz

      - name: Grant Full Access to c:\windows\temp directory
        run: icacls "C:\Windows\Temp" /q /c /t /grant Users:F /T

      - name: Install GStreamer
        working-directory: D:\a\strawberry\strawberry\downloads
        run: msiexec /a D:\a\strawberry\strawberry\downloads\gstreamer-1.0-msvc-x86_64-1.18.5.msi /passive /qn

      - name: Wait for GStreamer installation to complete
        run: Start-Sleep -s 20
        shell: powershell

      - name: Install GStreamer Devel
        working-directory: D:\a\strawberry\strawberry\downloads
        run: msiexec /a D:\a\strawberry\strawberry\downloads\gstreamer-1.0-devel-msvc-x86_64-1.18.5.msi /passive /qn

      - name: Wait for GStreamer Devel installation to complete
        run: Start-Sleep -s 30
        shell: powershell

      - name: Extract GnuTLS
        working-directory: D:\a\strawberry\strawberry
        run: |
          mkdir gnutls
          cd gnutls
          7z x d:\a\strawberry\strawberry\downloads\libgnutls_3.7.2_msvc14.zip
          xcopy /s /y bin\x64\*.* c:\gstreamer\1.0\msvc_x86_64\bin\
          xcopy /s /y lib\x64\*.* c:\gstreamer\1.0\msvc_x86_64\lib\
          xcopy /s /y include\* c:\gstreamer\1.0\msvc_x86_64\include\
          xcopy /s /y include\* c:\gstreamer\1.0\msvc_x86_64\include\

      - name: Extract TagLib
        working-directory: D:\a\strawberry\strawberry
        shell: bash
        run: tar -xvf /d/a/strawberry/strawberry/downloads/taglib-1.12.tar.gz

      - name: Fix pkg files
        shell: bash
        run: |
          sed -i 's/c:\/projects\/repos\/cerbero.git\/1.18\/build\/dist/c:\/gstreamer\/1.0/g' /c/gstreamer/1.0/msvc_x86_64/lib/pkgconfig/*.pc
          cp C:/vcpkg/packages/protobuf_x86-windows/lib/pkgconfig/protobuf.pc /c/gstreamer/1.0/msvc_x86_64/lib/pkgconfig/

      #- name: Compile Protobuf
      #  env:
      #    CL: "/MP"
      #  working-directory: D:\a\strawberry\strawberry\protobuf-3.18.0-rc-2
      #  run: |
      #    cd cmake
      #    mkdir build
      #    cd build
      #    cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -Dprotobuf_BUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX="d:/a/strawberry/strawberry/protobuf" -Dprotobuf_BUILD_TESTS=OFF
      #    nmake
      #    cmake --install .
      #    copy D:\a\strawberry\strawberry\protobuf-3.18.0-rc-2\cmake\build\protobuf.pc c:\gstreamer\1.0\msvc_x86_64\lib\pkgconfig\

      - name: Compile SQlite
        env:
          CL: "/MP"
        working-directory: D:\a\strawberry\strawberry\sqlite-autoconf-3360000
        run: nmake /f Makefile.msc

      - name: Check SQlite
        run: dir D:\a\strawberry\strawberry\sqlite-autoconf-3360000

      - name: Copy SQLite
        run: |
          copy d:\a\strawberry\strawberry\sqlite-autoconf-3360000\*.h c:\gstreamer\1.0\msvc_x86_64\include\
          copy d:\a\strawberry\strawberry\sqlite-autoconf-3360000\*.lib c:\gstreamer\1.0\msvc_x86_64\lib\
          copy d:\a\strawberry\strawberry\sqlite-autoconf-3360000\*.dll c:\gstreamer\1.0\msvc_x86_64\lib\
          copy d:\a\strawberry\strawberry\sqlite-autoconf-3360000\*.lib c:\gstreamer\1.0\msvc_x86_64\bin\
          copy d:\a\strawberry\strawberry\sqlite-autoconf-3360000\*.dll c:\gstreamer\1.0\msvc_x86_64\bin\

      - name: Compile TagLib
        env:
          CL: "/MP"
        working-directory: D:\a\strawberry\strawberry\taglib-1.12
        run: |
          mkdir build
          cd build
          cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="c:\gstreamer\1.0\msvc_x86_64"
          nmake
          cmake --install .

      - uses: actions/checkout@v1.2.0

      - name: Remove find_package(Boost)
        shell: bash
        run: sed -i 's/find_package(Boost.*//g' /d/a/strawberry/strawberry/CMakeLists.txt

      - name: Create Build Environment
        run: cmake -E make_directory build

      - name: Run CMake
        working-directory: build
        run: >
          cmake ..
          -DCMAKE_BUILD_TYPE=Release
          -DBUILD_WITH_QT6=ON
          -DBUILD_WERROR=OFF
          -DARCH=x86_64
          -DENABLE_WIN32_CONSOLE=OFF
          -DENABLE_DBUS=OFF
          -DENABLE_LIBGPOD=OFF
          -DENABLE_LIBMTP=OFF
          -DUSE_TAGLIB=ON
          -DPKG_CONFIG_EXECUTABLE=C:/gstreamer/1.0/msvc_x86_64/bin/pkg-config.exe
          -DSQLITE_INCLUDE_DIRS=c:/gstreamer/1.0/msvc_x86_64/lib/include
          -DSQLITE_LIBRARY_DIRS=c:/gstreamer/1.0/msvc_x86_64/lib
          -DSQLITE_LIBRARIES=c:/gstreamer/1.0/msvc_x86_64/lib/sqlite3.lib
          -DGNUTLS_LIBRARY=c:/gstreamer/1.0/msvc_x86_64/lib/gnutls.lib
          -DGNUTLS_INCLUDE_DIR=c:/gstreamer/1.0/msvc_x86_64/include
          -DGNUTLS_INCLUDE_DIRS=c:/gstreamer/1.0/msvc_x86_64/include
          -DBoost_INCLUDE_DIR=c:/gstreamer/1.0/msvc_x86_64/include
          -DBoost_INCLUDE_DIRS=c:/gstreamer/1.0/msvc_x86_64/include
          -DProtobuf_LIBRARY=c:/vcpkg/packages/protobuf_x64-windows/lib/libprotobuf.lib
          -DProtobuf_INCLUDE_DIR=c:/vcpkg/packages/protobuf_x64-windows/include
          -DProtobuf_INCLUDE_DIRS=c:/vcpkg/packages/protobuf_x64-windows/include
          -DPROTOBUF_PROTOC_EXECUTABLE=c:/vcpkg/packages/protobuf_x64-windows/tools/protobuf/protoc.exe

      - name: Run Make
        working-directory: build
        run: cmake --build . --config Release --parallel $(nproc)

      - name: Create directories
        working-directory: build
        run: mkdir gio-modules platforms styles tls sqldrivers imageformats gstreamer-plugins nsisplugins

      #- name: Copy GIO modules
      #  working-directory: build
      #  run: copy C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\libgiognutls.dll ${GITHUB_WORKSPACE}/build/gio-modules/

      - name: Copy Qt platform plugins
        working-directory: build
        run: copy d:/a/strawberry/qt/plugins/platforms/qwindows.dll ${GITHUB_WORKSPACE}/build/platforms/

      - name: Copy Qt styles
        working-directory: build
        run: copy d:/a/strawberry/qt//plugins/styles/qwindowsvistastyle.dll ${GITHUB_WORKSPACE}/build/styles/

      - name: Copy Qt TLS plugins
        working-directory: build
        run: copy d:/a/strawberry/qt//plugins/tls/*.dll ${GITHUB_WORKSPACE}/build/tls/

      - name: Copy Qt SQL drivers
        working-directory: build
        run: copy d:/a/strawberry/qt//plugins/sqldrivers/qsqlite.dll ${GITHUB_WORKSPACE}/build/sqldrivers/

      - name: Copy Qt imageformats plugins
        working-directory: build
        run: copy d:/a/strawberry/qt//plugins/imageformats/*.dll ${GITHUB_WORKSPACE}/build/imageformats/

      - name: Copy gstreamer plugins
        working-directory: build
        run: >
          copy
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstapp.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstcoreelements.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstaudioconvert.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstaudiofx.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstaudiomixer.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstaudioparsers.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstaudiorate.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstaudioresample.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstaudiotestsrc.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstautodetect.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstplayback.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstvolume.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstspectrum.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstequalizer.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstreplaygain.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gsttypefindfunctions.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstgio.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstdirectsound.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstwasapi.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstapetag.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gsticydemux.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstid3demux.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gsttcp.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstudp.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstsoup.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstcdio.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstrtp.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstrtsp.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstflac.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstwavparse.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstwavpack.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstogg.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstvorbis.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstopus.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstopusparse.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstspeex.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstlame.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstaiff.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstisomp4.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstasf.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstasfmux.dll
          C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstlibav.dll
          ${GITHUB_WORKSPACE}/build/gstreamer-plugins/

      - name: Copy extra binaries
        working-directory: build
        run: |
          copy d:\a\strawberry\strawberry\sqlite-autoconf-3360000\sqlite3.exe
          copy C:\gstreamer\1.0\msvc_x86_64\bin\gst-launch-1.0.exe
          copy C:\gstreamer\1.0\msvc_x86_64\bin\gst-discoverer-1.0.exe

      - name: Download copydlldeps.sh
        shell: bash
        working-directory: build
        run: wget https://raw.githubusercontent.com/strawberrymusicplayer/strawberry-mxe/master/tools/copydlldeps.sh

      - name: Copy dependencies
        shell: bash
        working-directory: build
        run: >
          copydlldeps.sh
          -c
          -d .
          -F .
          -F ./platforms
          -F ./styles
          -F ./tls
          -F ./sqldrivers
          -F ./imageformats
          -F ./gstreamer-plugins
          -R /d/a/strawberry/qt
          -R /c/gstreamer/1.0/msvc_x86_64

      - name: Strip binaries
        shell: bash
        working-directory: build
        run: find . -type f \( -iname \*.dll -o -iname \*.exe \) -exec /usr/src/strawberry-mxe/usr/bin/x86_64-w64-mingw32.shared-strip {} \;

      - name: Copy nsis files
        working-directory: build
        run: copy ${GITHUB_WORKSPACE}/dist/windows/*.nsi ${GITHUB_WORKSPACE}/dist/windows/*.nsh ${GITHUB_WORKSPACE}/dist/windows/*.ico .

      - name: Copy COPYING license file
        working-directory: build
        run: copy ${GITHUB_WORKSPACE}/COPYING .

      #- name: Build Windows installer
      #  working-directory: build
      #  run: makensis strawberry.nsi
